# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PiS5',
                'doc_host': 'https://pralinor.github.io',
                'git_url': 'https://github.com/pralinor/PiS5',
                'lib_path': 'PiS5'},
  'syms': {'PiS5.core': {'PiS5.core.foo': ('core.html#foo', 'PiS5/core.py')}}}
